<?php $__env->startSection('title', 'Reports'); ?>
<?php $__env->startSection('heading', 'Reports'); ?>
<?php $__env->startSection('subheading', 'Generate and review inventory reports'); ?>

<?php $__env->startSection('content'); ?>
<div class="stack">
    <div class="grid cols-3">
        <div class="card shadow">
            <div style="font-size:26px">🧴</div>
            <h3 style="margin:8px 0 4px">Stock Balance</h3>
            <div class="muted small" style="min-height:38px">Monthly stock movement following the clinic stock balance worksheet</div>
            <form method="POST" action="<?php echo e(route('reports.generate')); ?>">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="type" value="Stock Balance">
                <button type="submit" class="btn primary" style="margin-top:12px">Generate report</button>
            </form>
        </div>

        <div class="card shadow">
            <div style="font-size:26px">🧾</div>
            <h3 style="margin:8px 0 4px">Transaction History</h3>
            <div class="muted small" style="min-height:38px">Adjustment, disposal, issuance, and receiving transactions</div>
            <form method="POST" action="<?php echo e(route('reports.generate')); ?>">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="type" value="Transaction History">
                <div class="field" style="margin-top:10px">
                    <label>Transaction filter</label>
                    <select name="transaction_filter">
                        <option value="">All transactions</option>
                        <?php $__currentLoopData = \App\Models\TransactionLog::CANONICAL_TYPES; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $t): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <option value="<?php echo e($t); ?>"><?php echo e(ucfirst(strtolower($t))); ?></option>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </select>
                </div>
                <div class="field">
                    <label>Item type</label>
                    <select name="item_category_filter">
                        <option value="">All item types</option>
                        <option value="medicine">Medicine</option>
                        <option value="supply">Supply</option>
                        <option value="equipment">Equipment</option>
                    </select>
                </div>
                <button type="submit" class="btn primary" style="margin-top:12px">Generate report</button>
            </form>
        </div>

        <div class="card shadow">
            <div style="font-size:26px">🩺</div>
            <h3 style="margin:8px 0 4px">Equipment Registry / Status</h3>
            <div class="muted small" style="min-height:38px">Monthly clinic equipment/items inventory following the equipment report worksheet</div>
            <form method="POST" action="<?php echo e(route('reports.generate')); ?>">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="type" value="Equipment Registry / Status">
                <div class="field" style="margin-top:10px">
                    <label>Clinic site</label>
                    <select name="equipment_site">
                        <?php $__currentLoopData = $locations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $loc): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <option value="<?php echo e($loc); ?>"><?php echo e($loc); ?></option>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </select>
                </div>
                <button type="submit" class="btn primary" style="margin-top:12px">Generate report</button>
            </form>
        </div>
    </div>

    <div class="card">
        <div class="card-head">
            <h2>Past report records</h2>
            <div class="search-wrap"><input type="text" data-table-search="reportTable" placeholder="Search reports"></div>
        </div>
        <div class="table-wrap">
            <table id="reportTable" data-enhance>
                <thead><tr><th data-sort="text">Report type</th><th data-sort="date">Generated</th><th>Generated by</th><th>Coverage</th><th></th></tr></thead>
                <tbody>
                <?php $__empty_1 = true; $__currentLoopData = $pastReports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                    <tr>
                        <td><b><?php echo e($r->type); ?></b></td>
                        <td class="mono nowrap" data-sort-value="<?php echo e($r->created_at); ?>"><?php echo e($r->created_at->format('d M Y')); ?></td>
                        <td><?php echo e($r->generatedBy->fullname ?? '—'); ?></td>
                        <td><?php echo e($r->period); ?></td>
                        <td><a href="<?php echo e(route('reports.show', $r)); ?>" class="btn small">Preview</a></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                    <tr class="empty-row"><td colspan="5" class="empty">No reports generated yet.</td></tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\cims\resources\views/reports/index.blade.php ENDPATH**/ ?>