@extends('layouts.app')
@section('title', 'Reports')
@section('heading', 'Reports')
@section('subheading', 'Generate and review inventory reports')

@section('content')
<div class="stack">
    <div class="grid cols-3">
        <div class="card shadow">
            <div style="font-size:26px">🧴</div>
            <h3 style="margin:8px 0 4px">Stock Balance</h3>
            <div class="muted small" style="min-height:38px">Monthly stock movement following the clinic stock balance worksheet</div>
            <form method="POST" action="{{ route('reports.generate') }}">
                @csrf
                <input type="hidden" name="type" value="Stock Balance">
                <button type="submit" class="btn primary" style="margin-top:12px">Generate report</button>
            </form>
        </div>

        <div class="card shadow">
            <div style="font-size:26px">🧾</div>
            <h3 style="margin:8px 0 4px">Transaction History</h3>
            <div class="muted small" style="min-height:38px">Adjustment, disposal, issuance, and receiving transactions</div>
            <form method="POST" action="{{ route('reports.generate') }}">
                @csrf
                <input type="hidden" name="type" value="Transaction History">
                <div class="field" style="margin-top:10px">
                    <label>Transaction filter</label>
                    <select name="transaction_filter">
                        <option value="">All transactions</option>
                        @foreach(\App\Models\TransactionLog::CANONICAL_TYPES as $t)
                            <option value="{{ $t }}">{{ ucfirst(strtolower($t)) }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="field">
                    <label>Item type</label>
                    <select name="item_category_filter">
                        <option value="">All item types</option>
                        <option value="medicine">Medicine</option>
                        <option value="supply">Supply</option>
                        <option value="equipment">Equipment</option>
                    </select>
                </div>
                <button type="submit" class="btn primary" style="margin-top:12px">Generate report</button>
            </form>
        </div>

        <div class="card shadow">
            <div style="font-size:26px">🩺</div>
            <h3 style="margin:8px 0 4px">Equipment Registry / Status</h3>
            <div class="muted small" style="min-height:38px">Monthly clinic equipment/items inventory following the equipment report worksheet</div>
            <form method="POST" action="{{ route('reports.generate') }}">
                @csrf
                <input type="hidden" name="type" value="Equipment Registry / Status">
                <div class="field" style="margin-top:10px">
                    <label>Clinic site</label>
                    <select name="equipment_site">
                        @foreach($locations as $loc)
                            <option value="{{ $loc }}">{{ $loc }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn primary" style="margin-top:12px">Generate report</button>
            </form>
        </div>
    </div>

    <div class="card">
        <div class="card-head">
            <h2>Past report records</h2>
            <div class="search-wrap"><input type="text" data-table-search="reportTable" placeholder="Search reports"></div>
        </div>
        <div class="table-wrap">
            <table id="reportTable" data-enhance>
                <thead><tr><th data-sort="text">Report type</th><th data-sort="date">Generated</th><th>Generated by</th><th>Coverage</th><th></th></tr></thead>
                <tbody>
                @forelse($pastReports as $r)
                    <tr>
                        <td><b>{{ $r->type }}</b></td>
                        <td class="mono nowrap" data-sort-value="{{ $r->created_at }}">{{ $r->created_at->format('d M Y') }}</td>
                        <td>{{ $r->generatedBy->fullname ?? '—' }}</td>
                        <td>{{ $r->period }}</td>
                        <td><a href="{{ route('reports.show', $r) }}" class="btn small">Preview</a></td>
                    </tr>
                @empty
                    <tr class="empty-row"><td colspan="5" class="empty">No reports generated yet.</td></tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
