@extends('layouts.app')
@section('title', $report->type)
@section('heading', $report->type === 'Equipment Registry / Status' ? 'Equipment Report' : $report->type.' Report')
@section('subheading', $report->period)
@section('top-actions')
    <a href="{{ route('reports.export.pdf', $report) }}" class="btn small primary no-print">Generate PDF</a>
    <a href="{{ route('reports.export.csv', $report) }}" class="btn small no-print">Export CSV</a>
    <a href="{{ route('reports.export.excel', $report) }}" class="btn small no-print">Export Excel</a>
    <a href="{{ route('reports.index') }}" class="btn small no-print">Back to Reports</a>
@endsection

@section('content')
@php $data = $report->data; $layout = $data['layout'] ?? ''; @endphp
<div class="card">
    <div class="muted small" style="margin-bottom:10px">Generated by {{ $report->generatedBy->fullname ?? '—' }} on {{ $report->created_at->format('d M Y H:i') }}. This preview shows the data exactly as it was when the report was generated.</div>

    @if($layout === 'stock-balance-monthly')
        <div style="font-weight:800;text-transform:uppercase;letter-spacing:.05em;margin-bottom:8px">{{ $data['month_label'] }}</div>
        <div class="table-wrap" style="max-height:65vh">
            <table style="min-width:1600px;font-size:11px">
                <thead>
                    <tr>
                        <th rowspan="2">Item</th>
                        <th rowspan="2">Running Bal</th>
                        <th rowspan="2">Total Monthly Dispensed</th>
                        <th rowspan="2">Beginning Inv</th>
                        @for($w = 1; $w <= 5; $w++)<th colspan="5">Week {{ $w }}</th>@endfor
                        <th rowspan="2">Actual Inv</th>
                        <th rowspan="2">Var</th>
                    </tr>
                    <tr>
                        @for($w = 0; $w < 5; $w++)
                            <th>DEL</th><th>Pullout/Returns</th><th>Issued</th><th>Dispensed</th><th>Ending Inv</th>
                        @endfor
                    </tr>
                </thead>
                <tbody>
                    @php $lastCategory = null; @endphp
                    @forelse($data['rows'] as $row)
                        @if($row['category'] !== $lastCategory)
                            <tr><td colspan="29" style="font-weight:800;background:#f2f4f3">{{ $row['category'] === 'medicine' ? 'MEDICINE AND SUPPLIES' : 'MEDICAL SUPPLIES' }}</td></tr>
                            @php $lastCategory = $row['category']; @endphp
                        @endif
                        <tr>
                            <td style="font-weight:650">{{ $row['item'] }}</td>
                            <td class="mono right">{{ $row['running_bal'] }}</td>
                            <td class="mono right">{{ $row['total_dispensed'] }}</td>
                            <td class="mono right">{{ $row['beginning_inv'] }}</td>
                            @foreach($row['weeks'] as $w)
                                <td class="mono right">{{ $w['del'] }}</td>
                                <td class="mono right">{{ $w['pullout'] }}</td>
                                <td class="mono right">{{ $w['issued'] }}</td>
                                <td class="mono right">{{ $w['dispensed'] }}</td>
                                <td class="mono right">{{ $w['ending_inv'] }}</td>
                            @endforeach
                            <td class="mono right">{{ $row['actual_inv'] }}</td>
                            <td class="mono right">{{ $row['var'] }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="29" class="empty">No data available for this report.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>

    @elseif($layout === 'equipment-monthly')
        <div style="border-bottom:1px solid #555;padding-bottom:4px;margin-bottom:6px"><b>CLINIC SITE:</b> {{ $data['clinic_site'] }}</div>
        <div style="font-weight:800;margin-bottom:10px">Monthly Clinic Equipment/Items Inventory</div>
        <div class="table-wrap" style="max-height:60vh">
            <table style="min-width:1460px;font-size:11px">
                <thead><tr><th>Property Number</th><th>Item</th>@foreach($data['months'] as $m)<th>{{ substr($m, 0, 3) }}</th>@endforeach</tr></thead>
                <tbody>
                @forelse($data['rows'] as $row)
                    @if($row['kind'] === 'section')
                        <tr><td colspan="{{ count($data['months']) + 2 }}" style="background:#838383;color:#fff;font-weight:800">{{ $row['label'] }}</td></tr>
                    @else
                        <tr style="{{ $row['kind'] === 'remarks' ? 'background:#ececec;font-size:10px' : '' }}">
                            <td class="mono">{{ $row['property_number'] }}</td>
                            <td style="{{ $row['kind'] === 'remarks' ? 'text-align:right;font-style:italic' : 'text-align:left;font-weight:650' }}">{{ $row['item'] }}</td>
                            @foreach($row['months'] as $m)<td class="mono" style="text-align:center">{{ $m }}</td>@endforeach
                        </tr>
                    @endif
                @empty
                    <tr><td colspan="{{ count($data['months'] ?? []) + 2 }}" class="empty">No data available for this report.</td></tr>
                @endforelse
                </tbody>
            </table>
        </div>
        <div style="background:#dceaf3;padding:8px 10px;margin-top:8px;display:grid;gap:5px">
            <div><b>PREPARED BY (SIGNATURE OVER PRINTED NAME):</b> {{ $data['prepared_by'] }}</div>
            <div><b>DATE SUBMITTED:</b> {{ \Illuminate\Support\Carbon::parse($data['date_submitted'])->format('d M Y') }}</div>
        </div>
        <div style="border:1px solid #4c5d67;background:#dbeaf4;padding:8px 10px;margin-top:10px;display:grid;gap:6px;max-width:600px;margin-left:auto">
            <div><b>REMARKS:</b> {!! implode('<br>', array_map('e', $data['notes'])) !!}</div>
            <div><b>PROPERTY NO:</b> {{ $data['property_note'] }}</div>
            <div><b>SUBMISSION DATE:</b> {{ $data['submission_note'] }}</div>
        </div>

    @else
        <div class="table-wrap">
            <table>
                <thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>User</th><th>Activity</th></tr></thead>
                <tbody>
                @forelse($data['rows'] ?? [] as $row)
                    <tr>
                        <td class="mono nowrap">{{ $row['date'] }}</td>
                        <td><span class="badge blue">{{ $row['type'] }}</span></td>
                        <td class="mono">{{ $row['reference'] }}</td>
                        <td>{{ $row['user'] }}</td>
                        <td>{{ $row['activity'] }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" class="empty">No data available for this report.</td></tr>
                @endforelse
                </tbody>
            </table>
        </div>
    @endif
</div>
@endsection
